version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    links:
      - "api"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      SERVER_API_ENDPOINT: http://api:3000/api
      PUBLIC_API_ENDPOINT: http://localhost:5000/api
    expose:
      - 3000
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    volumes:
      - ./api:/app
      - /app/node_modules
    links:
      - "mongodb"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DB_URI: mongodb://blog-admin:blog-password@mongodb:27017/simple_blog_DB
    expose:
      - 3000
    ports:
      - 5000:3000
    command: ["yarn", "develop"]

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_DB_USER: blog-admin
      MONGO_DB_PASSWORD: blog-password
      MONGO_DB_DATABASE: simple_blog_DB
    volumes:
      - ./db:/data/db
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
